### ISSUE TITLE
Check https://github.com/ga4gh/benchmarking-tools

### ISSUE THREAD

**Issue by woook** [moka-guys/benchmarking_tool#20]
Can we check that we are still compliant with GA4GH standards, and maybe check whether we can use the same back end as them now?

**Comment by andyb3** [comment]
Wasn't able to use the Docker container exported from precisionFDA because it included all ref genomes etc and so was very large. However have updated our DNAnexus app to use the same html reports as the ga4gh app on precisionFDA, and checked that running one of our WES samples through the precisionFDA site and our app produce same results (when running the precisionFDA app with vcfeval-partialcredit engine and other settings as default)
